title: <p align="center"> Sudhanshu Gupta </p>
logo: /assets/img/logo.png


  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  
  <br>




theme: jekyll-theme-minimal
