title: <p align="center"> Sudhanshu Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  
  <br>
  </p>



theme: jekyll-theme-minimal
